#ifndef WEB_UI_H
#define WEB_UI_H

static const char WEB_UI_HTML[] =
"<!doctype html><html lang=\"zh-CN\"><head>"
"<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover\">"
"<title>Heavy Punch FPV</title>"
"<style>"
":root{--safe-top:env(safe-area-inset-top,8px);--safe-bottom:env(safe-area-inset-bottom,8px);--bg:#05080d;--line:#26384a;--text:#eaf6ff;--muted:#93a8ba;--accent:#2dd4bf;--warn:#fbbf24;--bad:#ef4444}"
"*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,\"Segoe UI\",\"Microsoft YaHei\",sans-serif;touch-action:none;-webkit-user-select:none;user-select:none;-webkit-tap-highlight-color:transparent}"
"body{position:fixed;inset:0}.app{height:100%;display:grid;grid-template-rows:minmax(220px,54vh) minmax(270px,46vh);background:#05080d}"
".viewer{position:relative;min-height:0;background:#020406;border-bottom:1px solid var(--line)}.viewer img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;background:#020406}.top{position:absolute;top:calc(var(--safe-top) + 8px);left:10px;right:10px;display:flex;align-items:flex-start;justify-content:space-between;gap:10px;pointer-events:none}.badge{background:rgba(5,10,16,.72);border:1px solid rgba(125,211,252,.28);border-radius:8px;padding:8px 10px;backdrop-filter:blur(10px);box-shadow:0 10px 26px rgba(0,0,0,.34)}.brand{font-size:14px;font-weight:900;letter-spacing:.14em}.sub{margin-top:2px;font-size:11px;color:var(--muted)}.status{font-size:12px;font-weight:900;color:#fecaca}.status.ok{color:#b7f7d4}.offline{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.42);color:#b8c7d5;font-weight:900;letter-spacing:.06em}"
".controls{min-height:0;padding:12px 12px calc(var(--safe-bottom) + 12px);display:grid;grid-template-columns:1fr auto 1fr;gap:12px;background:linear-gradient(180deg,#0c141d,#101820)}.leverBox,.tiltBox{min-width:0;min-height:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px}.label{font-size:12px;font-weight:900;color:var(--muted);letter-spacing:.12em}.value{font-size:23px;font-weight:900;font-variant-numeric:tabular-nums}.slot{position:relative;width:min(29vw,136px);height:100%;max-height:286px;min-height:176px;border-radius:8px;border:1px solid #416078;background:linear-gradient(180deg,#08111b,#172333);box-shadow:inset 0 14px 28px #0009}.tiltBox .slot{width:82px;max-height:250px;min-height:164px}.zero{position:absolute;left:10px;right:10px;top:50%;height:2px;background:#6f86a3}.scale{position:absolute;left:50%;top:10px;bottom:10px;width:1px;background:#334963}.knob{position:absolute;left:10px;right:10px;height:52px;border-radius:8px;border:1px solid #a7fff0;background:linear-gradient(180deg,#5eead4,#0f766e);box-shadow:0 10px 18px #0009;display:flex;align-items:center;justify-content:center;color:#022c26;font-weight:1000}.tiltBox .knob{background:linear-gradient(180deg,#fde68a,#f59e0b);border-color:#fef3c7;color:#3b2500}.meter{height:7px;width:min(29vw,136px);background:#26364b;border-radius:999px;overflow:hidden}.fill{height:100%;width:0;background:var(--accent)}"
".actions{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px}.stop{border:1px solid #fecaca;background:linear-gradient(180deg,#fb7185,#b91c1c);color:white;width:118px;height:52px;border-radius:8px;font-size:15px;font-weight:1000;box-shadow:0 10px 22px #0009}.center,.shot{color:var(--text);text-decoration:none;text-align:center;font-size:12px;font-weight:900;background:#172333;border:1px solid #416078;border-radius:8px;padding:9px 10px;width:118px}.center{font-family:inherit}"
"@media (orientation:landscape){.app{grid-template-rows:minmax(150px,56vh) minmax(180px,44vh)}.controls{padding:10px 16px calc(var(--safe-bottom) + 10px)}.slot{max-height:200px;min-height:146px;width:min(22vw,126px)}.tiltBox .slot{width:76px;max-height:190px;min-height:138px}.meter{width:min(22vw,126px)}.value{font-size:21px}}"
"@media (max-height:620px){.app{grid-template-rows:48vh 52vh}.slot{min-height:136px}.value{font-size:19px}.stop{height:46px}}"
"</style></head><body>"
"<main class=\"app\">"
"<section class=\"viewer\"><img id=\"stream\" alt=\"FPV stream\"><div id=\"offline\" class=\"offline\">VIDEO LINK PENDING</div><div class=\"top\"><div class=\"badge\"><div class=\"brand\">HEAVY PUNCH</div><div class=\"sub\">FPV TRACK DRIVE</div></div><div id=\"status\" class=\"badge status\">CONTROL OFFLINE</div></div></section>"
"<section class=\"controls\">"
"<div class=\"leverBox\"><div class=\"label\">LEFT TRACK</div><div id=\"valueL\" class=\"value\">0%</div><div id=\"slotL\" class=\"slot\"><div class=\"scale\"></div><div class=\"zero\"></div><div id=\"knobL\" class=\"knob\">L</div></div><div class=\"meter\"><div id=\"fillL\" class=\"fill\"></div></div></div>"
"<div class=\"actions\"><div class=\"tiltBox\"><div class=\"label\">CAM TILT</div><div id=\"valueT\" class=\"value\">0%</div><div id=\"slotT\" class=\"slot\"><div class=\"scale\"></div><div class=\"zero\"></div><div id=\"knobT\" class=\"knob\">T</div></div></div><button id=\"centerTilt\" class=\"center\">CENTER</button><button id=\"stop\" class=\"stop\">STOP</button><a class=\"shot\" href=\"/capture.jpg\" target=\"_blank\" rel=\"noopener\">SNAPSHOT</a></div>"
"<div class=\"leverBox\"><div class=\"label\">RIGHT TRACK</div><div id=\"valueR\" class=\"value\">0%</div><div id=\"slotR\" class=\"slot\"><div class=\"scale\"></div><div class=\"zero\"></div><div id=\"knobR\" class=\"knob\">R</div></div><div class=\"meter\"><div id=\"fillR\" class=\"fill\"></div></div></div>"
"</section></main>"
"<script>"
"let ws=null,vws=null,L=0,R=0,T=0,lastTracks='',lastTilt='',lastTiltAt=0,retryTimer=0,videoRetry=0,lastUrl='';const statusEl=document.getElementById('status'),stream=document.getElementById('stream'),offline=document.getElementById('offline');"
"function setStatus(ok){statusEl.textContent=ok?'CONTROL ONLINE':'CONTROL OFFLINE';statusEl.className='badge status '+(ok?'ok':'')}"
"function connect(){if(ws&&(ws.readyState===0||ws.readyState===1))return;clearTimeout(retryTimer);ws=new WebSocket('ws://'+location.host+'/ws');ws.onopen=()=>{setStatus(true);lastTracks='';lastTilt='';sendTracks(true);sendTilt(true)};ws.onclose=()=>{setStatus(false);retryTimer=setTimeout(connect,450)};ws.onerror=()=>{setStatus(false);try{ws.close()}catch(e){}}}"
"function send(msg){if(ws&&ws.readyState===1)ws.send(msg)}function sendTracks(force){const msg='tracks:'+L+':'+R;if(force||msg!==lastTracks){send(msg);lastTracks=msg}}function sendTilt(force){const msg='tilt:'+T,now=Date.now();if((force||msg!==lastTilt)&&(force||now-lastTiltAt>80)){send(msg);lastTilt=msg;lastTiltAt=now}}"
"function clamp(v,a,b){return v<a?a:v>b?b:v}function draw(side,val){const slot=document.getElementById('slot'+side),knob=document.getElementById('knob'+side),value=document.getElementById('value'+side);const h=slot.clientHeight,kh=52,mid=(h-kh)/2,range=mid-2;knob.style.top=(mid-(val/100)*range)+'px';value.textContent=val+'%';if(side!=='T'){const fill=document.getElementById('fill'+side);fill.style.width=Math.abs(val)+'%';fill.style.background=val>=0?'#2dd4bf':'#fbbf24'}}"
"function bindTrack(side){const slot=document.getElementById('slot'+side);let active=false;function setY(y){const r=slot.getBoundingClientRect(),mid=r.top+r.height/2;let pct=Math.round(((mid-y)/(r.height/2))*100);pct=clamp(pct,-100,100);if(side==='L')L=pct;else R=pct;draw(side,pct);sendTracks(false)}function zero(){if(!active)return;active=false;if(side==='L')L=0;else R=0;draw(side,0);sendTracks(true)}slot.addEventListener('pointerdown',e=>{e.preventDefault();active=true;slot.setPointerCapture(e.pointerId);setY(e.clientY)});slot.addEventListener('pointermove',e=>{if(active){e.preventDefault();setY(e.clientY)}});slot.addEventListener('pointerup',zero);slot.addEventListener('pointercancel',zero);slot.addEventListener('lostpointercapture',zero)}"
"function bindTilt(){const slot=document.getElementById('slotT');function setY(y){const r=slot.getBoundingClientRect(),mid=r.top+r.height/2;T=clamp(Math.round(((mid-y)/(r.height/2))*100),-100,100);draw('T',T);sendTilt(false)}slot.addEventListener('pointerdown',e=>{e.preventDefault();slot.setPointerCapture(e.pointerId);setY(e.clientY)});slot.addEventListener('pointermove',e=>{if(e.buttons){e.preventDefault();setY(e.clientY)}})}"
"function centerTilt(){T=0;draw('T',0);sendTilt(true)}function allStop(){L=0;R=0;draw('L',0);draw('R',0);lastTracks='';send('stop')}function showFrame(blob){const url=URL.createObjectURL(blob);stream.onload=()=>{offline.style.display='none';if(lastUrl)URL.revokeObjectURL(lastUrl);lastUrl=url};stream.src=url}"
"function refreshMjpeg(){offline.textContent='MJPEG FALLBACK';offline.style.display='flex';stream.onload=()=>offline.style.display='none';stream.onerror=()=>{offline.textContent='VIDEO LINK LOST';offline.style.display='flex';setTimeout(connectVideo,900)};stream.src='http://'+location.hostname+':81/stream?t='+Date.now()}"
"function connectVideo(){if(vws&&(vws.readyState===0||vws.readyState===1))return;clearTimeout(videoRetry);offline.textContent='WS VIDEO PENDING';offline.style.display='flex';vws=new WebSocket('ws://'+location.host+'/video-ws');vws.binaryType='blob';vws.onopen=()=>{offline.textContent='WS VIDEO ONLINE'};vws.onmessage=e=>{if(e.data&&e.data.size>0)showFrame(e.data)};vws.onclose=()=>{videoRetry=setTimeout(refreshMjpeg,500)};vws.onerror=()=>{try{vws.close()}catch(e){}}}"
"window.addEventListener('load',()=>{draw('L',0);draw('R',0);draw('T',0);bindTrack('L');bindTrack('R');bindTilt();connect();connectVideo();setInterval(()=>{sendTracks(true);if(Date.now()-lastTiltAt>1000)sendTilt(true)},120);document.getElementById('centerTilt').addEventListener('pointerdown',e=>{e.preventDefault();centerTilt()});document.getElementById('stop').addEventListener('pointerdown',e=>{e.preventDefault();allStop()});window.addEventListener('resize',()=>{draw('L',L);draw('R',R);draw('T',T)});window.addEventListener('blur',allStop);document.addEventListener('visibilitychange',()=>{if(document.hidden)allStop()});document.addEventListener('gesturestart',e=>e.preventDefault());document.addEventListener('dblclick',e=>e.preventDefault());document.addEventListener('contextmenu',e=>e.preventDefault())});"
"</script></body></html>";

#endif
