#ifndef WEB_UI_H
#define WEB_UI_H

static const char WEB_UI_HTML[] =
"<!doctype html><html lang=\"zh-CN\"><head>"
"<meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no,viewport-fit=cover\">"
"<title>Heavy Punch FPV</title>"
"<style>"
":root{--safe-top:env(safe-area-inset-top,8px);--safe-bottom:env(safe-area-inset-bottom,8px);--bg:#05080d;--panel:#101820;--line:#26384a;--text:#eaf6ff;--muted:#93a8ba;--accent:#2dd4bf;--warn:#fbbf24;--bad:#ef4444}"
"*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font-family:system-ui,-apple-system,\"Segoe UI\",\"Microsoft YaHei\",sans-serif;touch-action:none;-webkit-user-select:none;user-select:none;-webkit-tap-highlight-color:transparent}"
"body{position:fixed;inset:0}.app{height:100%;display:grid;grid-template-rows:minmax(220px,52vh) minmax(280px,48vh);background:#05080d}"
".viewer{position:relative;min-height:0;background:#020406;border-bottom:1px solid var(--line)}.viewer img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;background:#020406}.top{position:absolute;top:calc(var(--safe-top) + 8px);left:10px;right:10px;display:flex;align-items:flex-start;justify-content:space-between;gap:10px;pointer-events:none}.badge{background:rgba(5,10,16,.7);border:1px solid rgba(125,211,252,.28);border-radius:8px;padding:8px 10px;backdrop-filter:blur(10px);box-shadow:0 10px 26px rgba(0,0,0,.34)}.brand{font-size:14px;font-weight:900;letter-spacing:.14em}.sub{margin-top:2px;font-size:11px;color:var(--muted)}.status{font-size:12px;font-weight:900;color:#fecaca}.status.ok{color:#b7f7d4}.offline{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:rgba(0,0,0,.42);color:#b8c7d5;font-weight:900;letter-spacing:.06em}"
".controls{min-height:0;padding:12px 12px calc(var(--safe-bottom) + 12px);display:grid;grid-template-columns:1fr auto 1fr;grid-template-rows:1fr auto;gap:12px;background:linear-gradient(180deg,#0c141d,#101820)}.leverBox{min-width:0;min-height:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px}.label{font-size:12px;font-weight:900;color:var(--muted);letter-spacing:.12em}.value{font-size:24px;font-weight:900;font-variant-numeric:tabular-nums}.slot{position:relative;width:min(30vw,140px);height:100%;max-height:300px;min-height:190px;border-radius:8px;border:1px solid #416078;background:linear-gradient(180deg,#08111b,#172333);box-shadow:inset 0 14px 28px #0009}.zero{position:absolute;left:10px;right:10px;top:50%;height:2px;background:#6f86a3}.scale{position:absolute;left:50%;top:10px;bottom:10px;width:1px;background:#334963}.knob{position:absolute;left:10px;right:10px;height:52px;border-radius:8px;border:1px solid #a7fff0;background:linear-gradient(180deg,#5eead4,#0f766e);box-shadow:0 10px 18px #0009;display:flex;align-items:center;justify-content:center;color:#022c26;font-weight:1000}.meter{height:7px;width:min(30vw,140px);background:#26364b;border-radius:999px;overflow:hidden}.fill{height:100%;width:0;background:var(--accent)}"
".actions{grid-column:2;grid-row:1/3;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:10px}.role{width:118px;display:grid;grid-template-columns:1fr;gap:5px}.role button{height:30px;border-radius:8px;border:1px solid #416078;background:#172333;color:var(--muted);font-size:11px;font-weight:900}.role button.active{border-color:#a7fff0;background:#164e63;color:#e0fffb}.stop{border:1px solid #fecaca;background:linear-gradient(180deg,#fb7185,#b91c1c);color:white;width:118px;height:52px;border-radius:8px;font-size:15px;font-weight:1000;box-shadow:0 10px 22px #0009}.shot{color:var(--text);text-decoration:none;text-align:center;font-size:12px;font-weight:900;background:#172333;border:1px solid #416078;border-radius:8px;padding:9px 10px;width:118px}.leverBox.disabled{opacity:.42}.leverBox.disabled .slot{border-color:#2b3c4f}.leverBox.disabled .knob{background:linear-gradient(180deg,#718096,#334155);border-color:#94a3b8;color:#111827}"
"@media (orientation:landscape){.app{grid-template-rows:minmax(160px,56vh) minmax(190px,44vh)}.controls{padding:10px 16px calc(var(--safe-bottom) + 10px)}.slot{max-height:210px;min-height:150px;width:min(22vw,132px)}.meter{width:min(22vw,132px)}.value{font-size:22px}}"
"@media (max-height:620px){.app{grid-template-rows:48vh 52vh}.slot{min-height:140px}.value{font-size:20px}.stop{height:46px}}"
"</style></head><body>"
"<main class=\"app\">"
"<section class=\"viewer\"><img id=\"stream\" alt=\"FPV stream\"><div id=\"offline\" class=\"offline\">VIDEO LINK PENDING</div><div class=\"top\"><div class=\"badge\"><div class=\"brand\">HEAVY PUNCH</div><div class=\"sub\">FPV TRACK DRIVE</div></div><div id=\"status\" class=\"badge status\">CONTROL OFFLINE</div></div></section>"
"<section class=\"controls\">"
"<div class=\"leverBox\"><div class=\"label\">LEFT TRACK</div><div id=\"valueL\" class=\"value\">0%</div><div id=\"slotL\" class=\"slot\"><div class=\"scale\"></div><div class=\"zero\"></div><div id=\"knobL\" class=\"knob\">L</div></div><div class=\"meter\"><div id=\"fillL\" class=\"fill\"></div></div></div>"
"<div class=\"actions\"><div class=\"role\"><button id=\"roleBoth\" data-role=\"both\">BOTH</button><button id=\"roleLeft\" data-role=\"left\">LEFT</button><button id=\"roleRight\" data-role=\"right\">RIGHT</button></div><button id=\"stop\" class=\"stop\">STOP</button><a class=\"shot\" href=\"/capture.jpg\" target=\"_blank\" rel=\"noopener\">SNAPSHOT</a></div>"
"<div class=\"leverBox\"><div class=\"label\">RIGHT TRACK</div><div id=\"valueR\" class=\"value\">0%</div><div id=\"slotR\" class=\"slot\"><div class=\"scale\"></div><div class=\"zero\"></div><div id=\"knobR\" class=\"knob\">R</div></div><div class=\"meter\"><div id=\"fillR\" class=\"fill\"></div></div></div>"
"</section></main>"
"<script>"
"let ws=null,L=0,R=0,last='',role='both';const statusEl=document.getElementById('status'),stream=document.getElementById('stream'),offline=document.getElementById('offline');"
"function setStatus(ok){statusEl.textContent=ok?'CONTROL ONLINE':'CONTROL OFFLINE';statusEl.className='badge status '+(ok?'ok':'')}"
"function applyState(msg){const p=msg.split(':');if(p.length!==3||p[0]!=='state')return false;L=clamp(parseInt(p[1],10)||0,-100,100);R=clamp(parseInt(p[2],10)||0,-100,100);draw('L',L);draw('R',R);last='tracks:'+L+':'+R;return true}"
"function connect(){if(ws&&(ws.readyState===0||ws.readyState===1))return;ws=new WebSocket('ws://'+location.host+'/ws');ws.onopen=()=>{setStatus(true);sendTracks(true)};ws.onmessage=e=>applyState(e.data);ws.onclose=()=>{setStatus(false);setTimeout(connect,1000)};ws.onerror=()=>setStatus(false)}"
"function send(msg){if(ws&&ws.readyState===1)ws.send(msg)}function commandForRole(){if(role==='left')return 'axis:L:'+L;if(role==='right')return 'axis:R:'+R;return 'tracks:'+L+':'+R}function sendTracks(force){const msg=commandForRole();if(force||msg!==last){send(msg);last=msg}}"
"function canControl(side){return role==='both'||(role==='left'&&side==='L')||(role==='right'&&side==='R')}function setRole(next){role=next;document.querySelectorAll('.role button').forEach(b=>b.classList.toggle('active',b.dataset.role===role));document.querySelector('.leverBox:first-child').classList.toggle('disabled',!canControl('L'));document.querySelector('.leverBox:last-child').classList.toggle('disabled',!canControl('R'));last='';sendTracks(true)}"
"function clamp(v,a,b){return v<a?a:v>b?b:v}function draw(side,val){const slot=document.getElementById('slot'+side),knob=document.getElementById('knob'+side),value=document.getElementById('value'+side),fill=document.getElementById('fill'+side);const h=slot.clientHeight,kh=52,mid=(h-kh)/2,range=mid-2;knob.style.top=(mid-(val/100)*range)+'px';value.textContent=val+'%';fill.style.width=Math.abs(val)+'%';fill.style.background=val>=0?'#2dd4bf':'#fbbf24'}"
"function bind(side){const slot=document.getElementById('slot'+side);let active=false;function setY(y){const r=slot.getBoundingClientRect();const mid=r.top+r.height/2;let pct=Math.round(((mid-y)/(r.height/2))*100);pct=clamp(pct,-100,100);if(side==='L')L=pct;else R=pct;draw(side,pct);sendTracks(false)}function zero(){if(!active)return;active=false;if(side==='L')L=0;else R=0;draw(side,0);sendTracks(true)}slot.addEventListener('pointerdown',e=>{if(!canControl(side))return;active=true;slot.setPointerCapture(e.pointerId);setY(e.clientY)});slot.addEventListener('pointermove',e=>{if(active)setY(e.clientY)});slot.addEventListener('pointerup',zero);slot.addEventListener('pointercancel',zero);slot.addEventListener('lostpointercapture',zero)}"
"function allStop(){L=0;R=0;draw('L',0);draw('R',0);last='';send('stop')}function refreshStream(){offline.textContent='VIDEO LINK PENDING';offline.style.display='flex';stream.src='http://'+location.hostname+':81/stream?t='+Date.now();setTimeout(()=>{if(stream.src)offline.style.display='none'},900)}"
"window.addEventListener('load',()=>{const q=new URLSearchParams(location.search).get('role');draw('L',0);draw('R',0);bind('L');bind('R');setRole(q==='left'||q==='right'?q:'both');document.querySelectorAll('.role button').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();setRole(b.dataset.role)}));connect();refreshStream();setInterval(()=>sendTracks(true),160);document.getElementById('stop').addEventListener('pointerdown',e=>{e.preventDefault();allStop()});stream.addEventListener('load',()=>offline.style.display='none');stream.addEventListener('error',()=>{offline.textContent='VIDEO LINK LOST';offline.style.display='flex';setTimeout(refreshStream,1200)});window.addEventListener('resize',()=>{draw('L',L);draw('R',R)});window.addEventListener('blur',allStop);document.addEventListener('visibilitychange',()=>{if(document.hidden)allStop()})});"
"</script></body></html>";

#endif
